# Generated by Django 4.2.30 on 2026-07-08 14:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("organizations", "0002_seed_default_organization"),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="nombre")),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        max_length=220,
                        unique=True,
                        verbose_name="identificador público",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="descripción")),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("business_round", "Ronda de negocios"),
                            ("fair", "Feria"),
                            ("exhibition", "Exposición"),
                            ("congress", "Congreso"),
                            ("training", "Capacitación"),
                            ("seminar", "Seminario"),
                            ("workshop", "Workshop"),
                            ("meeting", "Encuentro empresarial"),
                        ],
                        default="business_round",
                        max_length=20,
                        verbose_name="tipo",
                    ),
                ),
                (
                    "modality",
                    models.CharField(
                        choices=[
                            ("in_person", "Presencial"),
                            ("virtual", "Virtual"),
                            ("hybrid", "Híbrido"),
                        ],
                        default="in_person",
                        max_length=15,
                        verbose_name="modalidad",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Borrador"),
                            ("published", "Publicado"),
                            ("finished", "Finalizado"),
                            ("cancelled", "Cancelado"),
                        ],
                        default="draft",
                        max_length=12,
                        verbose_name="estado",
                    ),
                ),
                ("start_date", models.DateField(verbose_name="fecha de inicio")),
                ("end_date", models.DateField(verbose_name="fecha de fin")),
                (
                    "location",
                    models.CharField(blank=True, max_length=200, verbose_name="lugar / sede"),
                ),
                ("address", models.CharField(blank=True, max_length=255, verbose_name="dirección")),
                (
                    "cover",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="events/covers/",
                        verbose_name="imagen de portada",
                    ),
                ),
                (
                    "capacity",
                    models.PositiveIntegerField(blank=True, null=True, verbose_name="cupo total"),
                ),
                (
                    "general_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="precio entrada general",
                    ),
                ),
                ("is_public", models.BooleanField(default=True, verbose_name="visible al público")),
                (
                    "meeting_duration_minutes",
                    models.PositiveIntegerField(
                        default=30, verbose_name="duración de cada reunión (min)"
                    ),
                ),
                (
                    "meetings_per_company",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="reuniones por empresa"
                    ),
                ),
                (
                    "tables_count",
                    models.PositiveIntegerField(default=0, verbose_name="cantidad de mesas"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="creado")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="actualizado")),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="organizations.organization",
                        verbose_name="organización",
                    ),
                ),
            ],
            options={
                "verbose_name": "evento",
                "verbose_name_plural": "eventos",
                "ordering": ["-start_date"],
            },
        ),
        migrations.CreateModel(
            name="TimeBlock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("date", models.DateField(verbose_name="fecha")),
                ("start_time", models.TimeField(verbose_name="hora de inicio")),
                ("end_time", models.TimeField(verbose_name="hora de fin")),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="time_blocks",
                        to="events.event",
                        verbose_name="evento",
                    ),
                ),
            ],
            options={
                "verbose_name": "bloque horario",
                "verbose_name_plural": "bloques horarios",
                "ordering": ["date", "start_time"],
            },
        ),
        migrations.CreateModel(
            name="Table",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("number", models.PositiveIntegerField(verbose_name="número")),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tables",
                        to="events.event",
                        verbose_name="evento",
                    ),
                ),
            ],
            options={
                "verbose_name": "mesa",
                "verbose_name_plural": "mesas",
                "ordering": ["number"],
            },
        ),
        migrations.CreateModel(
            name="Activity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="título")),
                ("description", models.TextField(blank=True, verbose_name="descripción")),
                (
                    "activity_type",
                    models.CharField(
                        choices=[
                            ("talk", "Charla"),
                            ("exhibition", "Exposición"),
                            ("public_meeting", "Reunión pública"),
                            ("business_round", "Ronda de negocios"),
                            ("workshop", "Workshop"),
                            ("other", "Otra"),
                        ],
                        default="talk",
                        max_length=20,
                        verbose_name="tipo",
                    ),
                ),
                ("start", models.DateTimeField(verbose_name="inicio")),
                ("end", models.DateTimeField(blank=True, null=True, verbose_name="fin")),
                (
                    "room",
                    models.CharField(blank=True, max_length=120, verbose_name="sala / espacio"),
                ),
                (
                    "capacity",
                    models.PositiveIntegerField(blank=True, null=True, verbose_name="cupo"),
                ),
                (
                    "is_public",
                    models.BooleanField(default=True, verbose_name="abierta al público general"),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activities",
                        to="events.event",
                        verbose_name="evento",
                    ),
                ),
            ],
            options={
                "verbose_name": "actividad",
                "verbose_name_plural": "actividades",
                "ordering": ["start"],
            },
        ),
        migrations.AddConstraint(
            model_name="table",
            constraint=models.UniqueConstraint(
                fields=("event", "number"), name="unique_table_per_event"
            ),
        ),
    ]
