# Generated by Django 4.2.30 on 2026-07-08 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="requires_approval",
            field=models.BooleanField(
                default=False,
                help_text="Si está activo, las inscripciones quedan pendientes de aprobación.",
                verbose_name="requiere aprobación manual",
            ),
        ),
    ]
