# Generated by Django 4.2.30 on 2026-07-08 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0002_event_requires_approval"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="round_end_time",
            field=models.TimeField(blank=True, null=True, verbose_name="hora de fin de la ronda"),
        ),
        migrations.AddField(
            model_name="event",
            name="round_start_time",
            field=models.TimeField(
                blank=True, null=True, verbose_name="hora de inicio de la ronda"
            ),
        ),
    ]
