# Generated by Django 4.2.30 on 2026-07-08 14:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("companies", "0002_seed_rubros"),
    ]

    operations = [
        migrations.CreateModel(
            name="Favorite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="guardado el")),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favorited_by",
                        to="companies.company",
                        verbose_name="empresa guardada",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favorites",
                        to="companies.company",
                        verbose_name="empresa que guarda",
                    ),
                ),
            ],
            options={
                "verbose_name": "favorito",
                "verbose_name_plural": "favoritos",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ConnectionRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pendiente"),
                            ("accepted", "Aceptada"),
                            ("rejected", "Rechazada"),
                        ],
                        default="pending",
                        max_length=10,
                        verbose_name="estado",
                    ),
                ),
                ("message", models.CharField(blank=True, max_length=280, verbose_name="mensaje")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="enviada el")),
                (
                    "responded_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="respondida el"),
                ),
                (
                    "from_company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_connections",
                        to="companies.company",
                        verbose_name="empresa solicitante",
                    ),
                ),
                (
                    "to_company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="received_connections",
                        to="companies.company",
                        verbose_name="empresa destinataria",
                    ),
                ),
            ],
            options={
                "verbose_name": "solicitud de conexión",
                "verbose_name_plural": "solicitudes de conexión",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="favorite",
            constraint=models.UniqueConstraint(
                fields=("owner", "company"), name="unique_favorite_owner_company"
            ),
        ),
        migrations.AddConstraint(
            model_name="connectionrequest",
            constraint=models.UniqueConstraint(
                fields=("from_company", "to_company"), name="unique_connection_from_to"
            ),
        ),
    ]
