# Generated by Django 4.2.30 on 2026-07-08 13:44

from django.db import migrations, models

import apps.accounts.models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={"verbose_name": "usuario", "verbose_name_plural": "usuarios"},
        ),
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", apps.accounts.models.UserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name="user",
            name="username",
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(max_length=254, unique=True, verbose_name="correo electrónico"),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("superadmin", "Super Administrador"),
                    ("organization", "Organización"),
                    ("company", "Empresa"),
                    ("representative", "Representante"),
                ],
                default="company",
                max_length=20,
                verbose_name="rol",
            ),
        ),
    ]
