# Generated by Django 4.2.30 on 2026-07-08 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_user_organization"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("superadmin", "Super Administrador"),
                    ("organization", "Organización"),
                    ("company", "Empresa"),
                    ("representative", "Representante"),
                    ("attendee", "Asistente"),
                ],
                default="company",
                max_length=20,
                verbose_name="rol",
            ),
        ),
    ]
