import datetime

import pytest

pytestmark = pytest.mark.django_db


def test_slug_autogenerated(make_event):
    e = make_event(name="Ronda de Negocios Primavera")
    assert e.slug == "ronda-de-negocios-primavera"


def test_slug_unique(make_event):
    make_event(name="Feria Anual")
    e2 = make_event(name="Feria Anual")
    assert e2.slug == "feria-anual-2"


def test_is_free_and_upcoming(make_event):
    free = make_event(general_price=0)
    assert free.is_free is True
    assert free.is_upcoming is True

    paid = make_event(name="Pago", general_price=1500)
    assert paid.is_free is False


def test_past_event_not_upcoming(make_event):
    past = make_event(
        name="Viejo",
        start_date=datetime.date.today() - datetime.timedelta(days=10),
        end_date=datetime.date.today() - datetime.timedelta(days=9),
    )
    assert past.is_upcoming is False
