# Generated by Django 4.2.30 on 2026-07-08 14:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import apps.companies.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("organizations", "0002_seed_default_organization"),
    ]

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("razon_social", models.CharField(max_length=200, verbose_name="razón social")),
                (
                    "nombre_fantasia",
                    models.CharField(blank=True, max_length=200, verbose_name="nombre de fantasía"),
                ),
                (
                    "cuit",
                    models.CharField(
                        blank=True,
                        max_length=13,
                        null=True,
                        unique=True,
                        validators=[apps.companies.validators.validate_cuit],
                        verbose_name="CUIT",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        max_length=220,
                        unique=True,
                        verbose_name="identificador público",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="descripción")),
                (
                    "logo",
                    models.ImageField(
                        blank=True, null=True, upload_to="companies/logos/", verbose_name="logo"
                    ),
                ),
                ("website", models.URLField(blank=True, verbose_name="sitio web")),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="email de contacto"),
                ),
                ("phone", models.CharField(blank=True, max_length=50, verbose_name="teléfono")),
                ("linkedin", models.URLField(blank=True, verbose_name="LinkedIn")),
                ("instagram", models.URLField(blank=True, verbose_name="Instagram")),
                ("facebook", models.URLField(blank=True, verbose_name="Facebook")),
                ("address", models.CharField(blank=True, max_length=255, verbose_name="dirección")),
                ("city", models.CharField(blank=True, max_length=120, verbose_name="localidad")),
                (
                    "province",
                    models.CharField(blank=True, max_length=120, verbose_name="provincia"),
                ),
                (
                    "country",
                    models.CharField(
                        blank=True, default="Argentina", max_length=120, verbose_name="país"
                    ),
                ),
                (
                    "employees_count",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="cantidad de empleados"
                    ),
                ),
                (
                    "production_capacity",
                    models.TextField(blank=True, verbose_name="capacidad productiva"),
                ),
                ("certifications", models.TextField(blank=True, verbose_name="certificaciones")),
                ("is_public", models.BooleanField(default=True, verbose_name="perfil público")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="creado")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="actualizado")),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="organizations.organization",
                        verbose_name="organización",
                    ),
                ),
            ],
            options={
                "verbose_name": "empresa",
                "verbose_name_plural": "empresas",
                "ordering": ["razon_social"],
            },
        ),
        migrations.CreateModel(
            name="Rubro",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=120, unique=True, verbose_name="nombre")),
                (
                    "slug",
                    models.SlugField(max_length=140, unique=True, verbose_name="identificador"),
                ),
            ],
            options={
                "verbose_name": "rubro",
                "verbose_name_plural": "rubros",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="nombre")),
                ("description", models.TextField(blank=True, verbose_name="descripción")),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="services",
                        to="companies.company",
                        verbose_name="empresa",
                    ),
                ),
            ],
            options={
                "verbose_name": "servicio",
                "verbose_name_plural": "servicios",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="nombre")),
                ("description", models.TextField(blank=True, verbose_name="descripción")),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to="companies.company",
                        verbose_name="empresa",
                    ),
                ),
            ],
            options={
                "verbose_name": "producto",
                "verbose_name_plural": "productos",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Need",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("description", models.CharField(max_length=300, verbose_name="necesidad")),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="needs",
                        to="companies.company",
                        verbose_name="empresa",
                    ),
                ),
            ],
            options={
                "verbose_name": "necesidad",
                "verbose_name_plural": "necesidades",
                "ordering": ["description"],
            },
        ),
        migrations.AddField(
            model_name="company",
            name="rubro",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="companies",
                to="companies.rubro",
                verbose_name="rubro",
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="company",
                to=settings.AUTH_USER_MODEL,
                verbose_name="usuario",
            ),
        ),
    ]
