# Generated by Django 4.2.30 on 2026-07-08 18:03

import django.db.models.deletion
from django.db import migrations, models

import apps.accreditation.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("companies", "0002_seed_rubros"),
        ("registrations", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Participant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("first_name", models.CharField(max_length=120, verbose_name="nombre")),
                ("last_name", models.CharField(max_length=120, verbose_name="apellido")),
                ("cargo", models.CharField(blank=True, max_length=120, verbose_name="cargo")),
                ("email", models.EmailField(blank=True, max_length=254, verbose_name="email")),
                ("phone", models.CharField(blank=True, max_length=50, verbose_name="teléfono")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="creado")),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participants",
                        to="companies.company",
                        verbose_name="empresa",
                    ),
                ),
            ],
            options={
                "verbose_name": "representante",
                "verbose_name_plural": "representantes",
                "ordering": ["last_name", "first_name"],
            },
        ),
        migrations.CreateModel(
            name="Accreditation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        default=apps.accreditation.models._generate_code,
                        max_length=32,
                        unique=True,
                        verbose_name="código",
                    ),
                ),
                (
                    "checked_in_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="ingreso"),
                ),
                (
                    "checked_out_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="egreso"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="creada")),
                (
                    "participant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="accreditations",
                        to="accreditation.participant",
                        verbose_name="representante",
                    ),
                ),
                (
                    "registration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="accreditations",
                        to="registrations.registration",
                        verbose_name="inscripción",
                    ),
                ),
            ],
            options={
                "verbose_name": "acreditación",
                "verbose_name_plural": "acreditaciones",
                "ordering": ["-created_at"],
            },
        ),
    ]
