import pytest

from apps.accounts.models import User
from apps.companies.models import Company
from apps.organizations.services import get_default_organization

pytestmark = pytest.mark.django_db


@pytest.fixture
def company_user():
    org = get_default_organization()
    return User.objects.create_user(
        email="empresa@test.com",
        password="RondaSegura123",
        role=User.Role.COMPANY,
        organization=org,
    )


def test_slug_autogenerated(company_user):
    c = Company.objects.create(
        user=company_user,
        organization=company_user.organization,
        razon_social="Metalúrgica del Sur SA",
    )
    assert c.slug == "metalurgica-del-sur-sa"


def test_slug_is_unique(company_user):
    org = company_user.organization
    Company.objects.create(user=company_user, organization=org, razon_social="Acme SA")
    other_user = User.objects.create_user(
        email="e2@test.com", password="RondaSegura123", role=User.Role.COMPANY, organization=org
    )
    c2 = Company.objects.create(user=other_user, organization=org, razon_social="Acme SA")
    assert c2.slug == "acme-sa-2"


def test_display_name_prefers_nombre_fantasia(company_user):
    c = Company.objects.create(
        user=company_user,
        organization=company_user.organization,
        razon_social="Larga Razón Social SA",
        nombre_fantasia="AcmeCorp",
    )
    assert c.display_name == "AcmeCorp"


def test_rubros_seeded():
    from apps.companies.models import Rubro

    assert Rubro.objects.filter(slug="tecnologia-y-software").exists()
