# Generated by Django 4.2.30 on 2026-07-08 16:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("events", "0002_event_requires_approval"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Registration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pendiente"),
                            ("confirmed", "Confirmada"),
                            ("rejected", "Rechazada"),
                            ("cancelled", "Cancelada"),
                        ],
                        default="pending",
                        max_length=12,
                        verbose_name="estado",
                    ),
                ),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("not_required", "Sin costo"),
                            ("simulated", "Pago simulado"),
                            ("pending", "Pago pendiente"),
                        ],
                        default="not_required",
                        max_length=15,
                        verbose_name="pago",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=10, verbose_name="monto"
                    ),
                ),
                ("note", models.CharField(blank=True, max_length=280, verbose_name="nota")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="inscripto el"),
                ),
                (
                    "decided_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="resuelto el"),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="registrations",
                        to="events.event",
                        verbose_name="evento",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="registrations",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "inscripción",
                "verbose_name_plural": "inscripciones",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="registration",
            constraint=models.UniqueConstraint(
                fields=("event", "user"), name="unique_registration_event_user"
            ),
        ),
    ]
