# Generated by Django 4.2.30 on 2026-07-08 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("companies", "0002_seed_rubros"),
        ("organizations", "0002_seed_default_organization"),
    ]

    operations = [
        migrations.CreateModel(
            name="Match",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "score",
                    models.PositiveSmallIntegerField(default=0, verbose_name="compatibilidad (%)"),
                ),
                ("details", models.JSONField(blank=True, default=dict, verbose_name="desglose")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="actualizado")),
                (
                    "company_a",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="matches_as_a",
                        to="companies.company",
                        verbose_name="empresa A",
                    ),
                ),
                (
                    "company_b",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="matches_as_b",
                        to="companies.company",
                        verbose_name="empresa B",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="matches",
                        to="organizations.organization",
                        verbose_name="organización",
                    ),
                ),
            ],
            options={
                "verbose_name": "match",
                "verbose_name_plural": "matches",
                "ordering": ["-score"],
            },
        ),
        migrations.AddConstraint(
            model_name="match",
            constraint=models.UniqueConstraint(
                fields=("company_a", "company_b"), name="unique_match_pair"
            ),
        ),
    ]
