# Generated by Django 4.2.30 on 2026-07-08 16:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("events", "0003_event_round_end_time_event_round_start_time"),
        ("companies", "0002_seed_rubros"),
    ]

    operations = [
        migrations.CreateModel(
            name="MeetingRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pendiente"),
                            ("accepted", "Aceptada"),
                            ("rejected", "Rechazada"),
                            ("cancelled", "Cancelada"),
                        ],
                        default="pending",
                        max_length=10,
                        verbose_name="estado",
                    ),
                ),
                ("message", models.CharField(blank=True, max_length=280, verbose_name="mensaje")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="solicitada el"),
                ),
                (
                    "responded_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="respondida el"),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="meeting_requests",
                        to="events.event",
                        verbose_name="evento",
                    ),
                ),
                (
                    "from_company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_meeting_requests",
                        to="companies.company",
                        verbose_name="empresa solicitante",
                    ),
                ),
                (
                    "time_block",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="meeting_requests",
                        to="events.timeblock",
                        verbose_name="bloque horario propuesto",
                    ),
                ),
                (
                    "to_company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="received_meeting_requests",
                        to="companies.company",
                        verbose_name="empresa destinataria",
                    ),
                ),
            ],
            options={
                "verbose_name": "solicitud de reunión",
                "verbose_name_plural": "solicitudes de reunión",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Meeting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("confirmed", "Confirmada"), ("cancelled", "Cancelada")],
                        default="confirmed",
                        max_length=10,
                        verbose_name="estado",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="creada el")),
                (
                    "company_a",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="meetings_as_a",
                        to="companies.company",
                        verbose_name="empresa A",
                    ),
                ),
                (
                    "company_b",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="meetings_as_b",
                        to="companies.company",
                        verbose_name="empresa B",
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="meetings",
                        to="events.event",
                        verbose_name="evento",
                    ),
                ),
                (
                    "request",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="meeting",
                        to="meetings.meetingrequest",
                        verbose_name="solicitud",
                    ),
                ),
                (
                    "table",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="meetings",
                        to="events.table",
                        verbose_name="mesa",
                    ),
                ),
                (
                    "time_block",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="meetings",
                        to="events.timeblock",
                        verbose_name="bloque horario",
                    ),
                ),
            ],
            options={
                "verbose_name": "reunión",
                "verbose_name_plural": "reuniones",
                "ordering": ["time_block__date", "time_block__start_time"],
            },
        ),
        migrations.AddConstraint(
            model_name="meetingrequest",
            constraint=models.UniqueConstraint(
                fields=("from_company", "to_company", "time_block"), name="unique_meeting_request"
            ),
        ),
    ]
