# Generated by Django 4.2.30 on 2026-07-08 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Organization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="nombre")),
                ("slug", models.SlugField(unique=True, verbose_name="identificador")),
                ("description", models.TextField(blank=True, verbose_name="descripción")),
                (
                    "logo",
                    models.ImageField(
                        blank=True, null=True, upload_to="organizations/logos/", verbose_name="logo"
                    ),
                ),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="email de contacto"),
                ),
                ("phone", models.CharField(blank=True, max_length=50, verbose_name="teléfono")),
                ("website", models.URLField(blank=True, verbose_name="sitio web")),
                ("is_active", models.BooleanField(default=True, verbose_name="activa")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="fecha de creación"),
                ),
            ],
            options={
                "verbose_name": "organización",
                "verbose_name_plural": "organizaciones",
                "ordering": ["name"],
            },
        ),
    ]
