# Generated by Django 4.2.30 on 2026-07-08 18:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("title", models.CharField(max_length=180, verbose_name="título")),
                ("message", models.CharField(blank=True, max_length=300, verbose_name="mensaje")),
                ("url", models.CharField(blank=True, max_length=300, verbose_name="enlace")),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("info", "Información"),
                            ("success", "Éxito"),
                            ("warning", "Aviso"),
                        ],
                        default="info",
                        max_length=10,
                        verbose_name="nivel",
                    ),
                ),
                ("is_read", models.BooleanField(default=False, verbose_name="leída")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="fecha")),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="destinatario",
                    ),
                ),
            ],
            options={
                "verbose_name": "notificación",
                "verbose_name_plural": "notificaciones",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("body", models.TextField(verbose_name="mensaje")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="enviado el")),
                ("read_at", models.DateTimeField(blank=True, null=True, verbose_name="leído el")),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="received_messages",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="destinatario",
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_messages",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="remitente",
                    ),
                ),
            ],
            options={
                "verbose_name": "mensaje",
                "verbose_name_plural": "mensajes",
                "ordering": ["created_at"],
            },
        ),
    ]
